[package]
name = "agntcy-shadi-py"
version = "0.1.9"
edition = "2021"
description = "PyO3 Python bindings for SHADI runtime services."
license.workspace = true
repository.workspace = true

[lib]
name = "shadi"
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
agent_secrets = { package = "agntcy-shadi-agent-secrets", version = "0.3.0", path = "../agent_secrets", features = ["onepassword"] }
shadi_memory = { package = "agntcy-shadi-memory", version = "0.2.0", path = "../shadi_memory" }
shadi_sandbox = { package = "agntcy-shadi-sandbox", version = "0.2.1", path = "../shadi_sandbox" }
shadi_telemetry = { package = "agntcy-shadi-telemetry", version = "0.1.2", path = "../shadi_telemetry" }
tracing = "0.1"

[dependencies.pyo3]
version = "0.29"
features = ["extension-module"]

[build-dependencies]
pyo3-build-config = "0.29"
